version: '3.8'

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WP_VOLUME}
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_VOLUME}

networks:
  inception-network:
    name: inception-network

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    env_file:
      - .env
    depends_on:
      - wordpress
    networks:
      - inception-network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    env_file:
      - .env
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception-network
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb:11.4
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception-network
    restart: always
