volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WP_VOLUME}
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_VOLUME}

networks:
  inception-network:
    name: inception-network

# Secrets are used to store the passwords for the database and the WordPress site
secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_password:
    file: ../secrets/wp_password.txt
  wp_author_password:
    file: ../secrets/wp_author_password.txt
  redis_password:
    file: ../secrets/redis_password_bonus.txt
  ftp_password:
    file: ../secrets/ftp_password_bonus.txt

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html:ro #read-only access
    networks:
      - inception-network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    env_file:
      - .env
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MARIA_USER}
      WORDPRESS_DB_NAME: ${MARIA_DATABASE}
    secrets:
      - db_password
      - wp_password
      - wp_author_password
      - redis_password
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
      - redis
    networks:
      - inception-network
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    env_file:
      - .env
    # environment:
    #   MARIA_DATABASE: ${MARIA_DATABASE}
    #   MARIA_USER: ${MARIA_USER}
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception-network
    restart: always

  # Bonus services
  redis:
    container_name: redis
    build: ./requirements/bonus/redis/.
    env_file:
      - .env
    secrets:
      - redis_password
    networks:
      - inception-network
    restart: always

  ftp-server:
    container_name: ftp-server
    build: ./requirements/bonus/ftp-server/.
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    env_file:
      - .env
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      FTP_USER: ${FTP_USER:-wpftp}
      FTP_PASV_ADDRESS: ${FTP_PASV_ADDRESS:-}
      FTP_PORT: ${FTP_PORT:-21}
    secrets:
      - ftp_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception-network
    restart: always
